[package]
name = "aurora-effect-solver"
version = "0.1.0"
edition = "2021"
authors = ["Aurora Research Team"]
description = "Prototype algebraic effect row solver for Aurora"
license = "Apache-2.0"

[dependencies]
thiserror = "1.0"
indexmap = "2.2"

[dev-dependencies]
proptest = "1.4"
